name: "Create Build Info"
description: "Generates buildInfo.json, CHANGELOG.md, version.inc, and optionally commits the changelog."
author: "Magnus Gule <magnus.gule@piscada.com>"
inputs:
  artifact-name:
    description: "Name of the artifact to upload."
    required: true
    type: string
  push-changelog:
    description: "Whether to commit and push the `CHANGELOG.md`, `version.inc`, and `buildInfo.json` files."
    required: false
    default: false
    type: boolean
outputs:
  version_fullsemver:
    description: "Full semantic version."
    value: ${{ env.fullsemver }}
  version_majorminorpatch:
    description: "Major.Minor.Patch version."
    value: ${{ env.majorminorpatch }}
  version_prereleasetag:
    description: "Pre-release tag."
    value: ${{ env.pre_releaselabel }}
runs:
  using: "composite"
  steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        fetch-depth: 0 # Ensure full history for versioning

    - name: Remove Extra Git Remotes
      run: ./scripts/remove_git_remotes.sh
      shell: bash

    - name: Set Version Information
      run: ./scripts/set_version.sh
      shell: bash

    - name: Save FullSemVer to version.inc
      run: ./scripts/save_version_inc.sh
      shell: bash

    - name: Generate CHANGELOG.md
      run: ./scripts/generate_changelog.sh
      shell: bash

    - name: Commit and Push CHANGELOG.md
      if: ${{ inputs.push-changelog == 'true' && github.ref == 'refs/heads/main' }}
      run: ./scripts/commit_push_changelog.sh
      shell: bash

    - name: Upload build-info artifact
      uses: actions/upload-artifact@v4
      with:
        name: ${{ inputs.artifact-name }}
        path: |
          buildInfo.json
          CHANGELOG.md
          version.inc
